Upgrade Maven Javadoc Plugin 3.0.0.
Failed to execute goal javadoc:javadoc (default-cli) on project maven-report: An error has occurred in Javadoc report generation:
Exit code: 1 - CSonarReportMojo.java:35: error:
 - unknown tag: goal
 - unknown tag: parameter
 - unknown tag: required
 - unknown tag: readonly
 - unknown tag: component